// frontend/src/components/LandingPage.tsx
import { useLandingPageStore } from "@/stores"

export default function LandingPage() {
    const landingPageStore = useLandingPageStore()
    function exitLandingPage() {
        landingPageStore.setHasExited()
    }

    return (
        <div className="bg-green flex h-screen flex-col items-center justify-center">
            <div className="text-text-color text-[32px] font-bold">
                Landing Page
            </div>
            <button
                className="bg-green-dark text-button-text hover:bg-green cursor-pointer rounded-[5px] p-[10px_20px] transition-[background-color] duration-200"
                onClick={exitLandingPage}
            >
                Let's Go
            </button>
        </div>
    )
}

// frontend/src/components/LandingPage.vue
<script setup lang="ts">
import { useLandingPageStore } from "@/stores/landingPage"

const landingPageStore = useLandingPageStore()

function exitLandingPage() {
  landingPageStore.setHasExited()
}
</script>

<template>
  <div class="container">
    <h1>Landing Page</h1>
    <button class="exit" @click="exitLandingPage">Let's Go</button>
  </div>
</template>

<style scoped>
.container {
  background: var(--green);
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.exit {
  background: var(--green-dark);
  color: var(--button-text);
  padding: 10px 20px;
  border-radius: 5px;
  transition: background-color 0.2s;
}

.exit:hover {
  background: var(--green);
}
</style>
