// frontend/src/components/MainPage.tsx
import { Sidebar } from "@/components/sidebar"
import Editor from "@/components/Editor"
import PDFViewer from "@/components/pdf/PDFViewer.tsx"

export default function MainPage() {
    return (
        <div className="bg-paper-yellow flex h-screen flex-row justify-between">
            <Sidebar />
            <Editor />
            <PDFViewer />
        </div>
    )
}

// frontend/src/components/MainPage.vue
<script setup lang="ts">
import SideBar from "@/components/SideBar.vue"
import Editor from "@/components/Editor.vue"
import PDFViewer from "@/components/PDFViewer.vue"
</script>

<template>
  <div class="main">
    <SideBar />
    <Editor />
    <PDFViewer />
  </div>
</template>

<style scoped>
.main {
  background: var(--paper-yellow);
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  height: 100vh;
}
</style>
