// frontend/src/App.tsx
import LandingPage from "@/components/LandingPage.tsx"
import { useLandingPageStore } from "@/stores"
import MainPage from "@/components/MainPage.tsx"

export default function App() {
    const { hasExited } = useLandingPageStore()

    return (
        <div className="font-[Arial,_sans-serif]">
            {!hasExited && <LandingPage />}
            {hasExited && <MainPage />}
        </div>
    )
}

// frontend/src/App.vue
<script setup lang="ts">
import { useLandingPageStore } from "@/stores/landingPage"
import LandingPage from "@/components/LandingPage.vue"
import { computed } from "vue"
import MainPage from "@/components/MainPage.vue"

const landingPageStore = useLandingPageStore()

const hasExited = computed(() => landingPageStore.hasExited)
</script>

<template>
  <main>
    <LandingPage v-if="!hasExited" />
    <MainPage v-else />
  </main>
</template>

<style scoped></style>
